# GET http://localhost:8080/
GET http://localhost:8080/users/users
###

POST http://localhost:8080/users/register
Content-Type: application/json

{
    "firstName": "Devindu",
    "lastName": "Samarasinghe",
    "email": "devindu99@gmail.com",
    "password": "123456",
    "role": "customer"
}